chore: Update OpenStack credentials handling and environment variables in cronjob script
Signed-off-by: Specter <spectertj@gmail.com>

diff --git a/cronjob/configmap.yaml b/cronjob/configmap.yaml
--- a/cronjob/configmap.yaml
+++ b/cronjob/configmap.yaml
@@ -34,42 +34,42 @@ data:
     touch /tmp/reports/report_done
     ls /tmp/reports
 
-  upload.sh: |
-    #!/bin/sh
+#   upload.sh: |
+#     #!/bin/sh
 
-    # Load credentials from the OpenStack credentials file
-    vault_path="/etc/openstack/credentials"
-    if [ -f "$vault_path" ]; then
-        while IFS='=' read -r key value; do
-            export "$key"="$value"
-        done < "$vault_path"
-    else
-        echo "Error: Vault credentials file not found at $vault_path"
-        exit 1
-    fi
+#     # Load credentials from the OpenStack credentials file
+#     vault_path="/etc/openstack/credentials"
+#     if [ -f "$vault_path" ]; then
+#         while IFS='=' read -r key value; do
+#             export "$key"="$value"
+#         done < "$vault_path"
+#     else
+#         echo "Error: Vault credentials file not found at $vault_path"
+#         exit 1
+#     fi
 
-    # Config environment variables
-    export OS_PROJECT_NAME="your-bucket-s3"
-    export OS_AUTH_URL="https://api.wavestack.de:5000"
-    export OS_PROJECT_NAME="project_name"
-    export OS_AUTH_TYPE="v3applicationcredential"
+#     # Config environment variables
+#     export OS_PROJECT_NAME="your-bucket-s3"
+#     export OS_AUTH_URL="https://api.wavestack.de:5000"
+#     export OS_PROJECT_NAME="project_name"
+#     export OS_AUTH_TYPE="v3applicationcredential"
 
-    # Report directory and OpenStack container name
-    report_directory="/tmp/reports"
-    container_name="object_storage_container_name"
+#     # Report directory and OpenStack container name
+#     report_directory="/tmp/reports"
+#     container_name="object_storage_container_name"
 
-    # Proccess and upload JSON files to OpenStack container
-    for file_path in "$report_directory"/*.json; do
-        if [ -f "$file_path" ]; then
-            object_name="scan_results/$(basename "$file_path")"
-            openstack object create "$container_name" "$file_path" --name "$object_name"
-            if [ $? -ne 0 ]; then
-                echo "Error: Failed to upload $file_path to $container_name/$object_name"
-                exit 1
-            else
-                echo "Uploaded $file_path to $container_name/$object_name successfully."
-            fi
-        else
-            echo "No JSON files found in $report_directory."
-        fi
-    done
+#     # Proccess and upload JSON files to OpenStack container
+#     for file_path in "$report_directory"/*.json; do
+#         if [ -f "$file_path" ]; then
+#             object_name="scan_results/$(basename "$file_path")"
+#             openstack object create "$container_name" "$file_path" --name "$object_name"
+#             if [ $? -ne 0 ]; then
+#                 echo "Error: Failed to upload $file_path to $container_name/$object_name"
+#                 exit 1
+#             else
+#                 echo "Uploaded $file_path to $container_name/$object_name successfully."
+#             fi
+#         else
+#             echo "No JSON files found in $report_directory."
+#         fi
+#     done
diff --git a/cronjob/trivy-cronjob.yaml b/cronjob/trivy-cronjob.yaml
--- a/cronjob/trivy-cronjob.yaml
+++ b/cronjob/trivy-cronjob.yaml
@@ -22,20 +22,35 @@ spec:
               subPath: "openstack"
             - mountPath: "/tmp/reports"
               name: "reports"
-          - name: trivy-reports-uploader
-            image: openstacktools/openstack-client
-            command: ["/bin/sh", "-c", "timeout=60; while [ ! -f /tmp/reports/report_done ] && [ $timeout -gt 0 ]; do sleep 1; timeout=$((timeout - 1)); done; [ ! -f /tmp/reports/report_done ] && { echo 'Error: report_done file not found after waiting.'; exit 1; }; cp /scripts/upload.sh /tmp/upload.sh && chmod +x /tmp/upload.sh && /tmp/upload.sh"]
+          - name: "trivy-reports-uploader"
+            image: "ghcr.io/gtema/openstack"
+            command:
+              - "/bin/sh"
+              - "-c"
+            args:
+              - |
+                timeout=60; \
+                while [ ! -f /tmp/reports/report_done ] && [ $timeout -gt 0 ]; do \
+                  sleep 1; \
+                  timeout=$((timeout - 1)); \
+                done; \
+                if [ ! -f /tmp/reports/report_done ]; then \
+                  echo "Error: report_done file not found after waiting."; \
+                  exit 1; \
+                fi; \
+                cd /tmp/reports && \
+                for file in *.json; do \
+                  osc --os-cloud backup object-store object upload backup scan_results/${file} -vv; \
+                done
             envFrom:
-            - secretRef:
-                name: openstack-credentials
+              - secretRef:
+                  name: openstack-credentials
             volumeMounts:
-            - name: scripts
-              mountPath: "/scripts"
-            - mountPath: "/etc/openstack"
-              name: "cron-config"
-              subPath: "openstack"
-            - mountPath: "/tmp/reports"
-              name: "reports"
+              - mountPath: "/tmp/reports"
+                name: "reports"
+              - mountPath: "/etc/openstack"
+                name: "cron-config"
+                subPath: "openstack"
 
           
           volumes:
